config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "emails#index"
  resources :tasks, except: [:show]
  resources :emails
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :resource_name, :resource, :devise_mapping, :resource_class
	def resource_name
	  :user
	end

	def resource
	  @resource ||= User.new
	end

	def resource_class
	  User
	end

	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
before_action :set_email, only: [:show, :update, :destroy]

	def show
		@email.update(read: true)
		puts "ù"*100
		puts @email.id
		puts params
		puts "ù"*100
	end

	def index
    @emails = Email.all
  end

  def create
  	@email = Email.new(object: Faker::Book.title, body: Faker::Quotes::Shakespeare.hamlet_quote)
    if @email.save
    	respond_to do |format|
	      format.html { redirect_to root_path }
	      format.js { }
    	end
    else
      redirect_to root_path
    end
  end

  def update
  	@email.update(read: !@email.read)
    respond_to do |format|
	      format.html { redirect_to root_path }
	      format.js { }
    end
  end

  def destroy
    @email.destroy
    respond_to do |format|
	      format.html { redirect_to root_path }
	      format.js { }
    end
  end

  private

  def set_email
      @email = Email.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :authenticate_user!

  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    if @task.save
    	respond_to do |format|
	      format.html { redirect_to root_path }
	      format.js { }
    	end
      flash[:notice] = "Task created"
    else
      redirect_to root_path
      flash[:notice] = "Please try again"
    end
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all

  end

  def update
    @task = Task.find(params[:id])
    @task.status = !@task.status
    @task.update(task_params)
    respond_to do |format|
	      format.html { redirect_to tasks_path }
	      format.js { }
    end
    flash[:notice] = "Task edited"
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
	      format.html { redirect_to root_path }
	      format.js { }
    end
  end


  private

  def task_params
    params.permit(:title, :deadline, :description)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1 class="text-center mb-4">Welcome to my todolist app</h1>
<%= render 'layouts/task_form'  %>
<div class="container">
  <ul>
  <% @categories.each do  |category|%>

  <li class="category-title"><%= category.title  %></li>
  <div class="card">
	<div class="category-content category-<%= category.id %>">
	    <ul>
	      <% category.tasks.sort_by {|task|task.created_at}.each do |task|  %>

	      <li class="task-<%= task.id %>"
	      	<% if task.status %>
	      		style="text-decoration: line-through;"
	      	<% end %>
	      		 >
	      	<%= check_box_tag :name, 1, task.status , data: { remote: true, url: task_path(task), params: { id: task.id}.to_param, method: "put" }%>
	        <%= task.title  %>
	        <% unless task.deadline.nil? %>
	          , to read: <%= task.deadline.strftime('%D')  %>
	        <% end %>
	        <%= link_to fa_icon("trash"), task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
	      </li>
	      <% end %>
	    </ul>
	</div>
  </div>
  <% end %>
  </ul>
</div>

<div class="container text-center d-flex justify-content-center">
	<button id="previous"><-</button>
  	<div id="carousel">
    	<% @tasks.each do |task|  %>
        	<% unless task.image.nil? %>
          		<%= image_tag task.image, class: "rounded-circle carousel-img" %>
        	<% end %>

    	<% end %>
  	</div>
	<button id="next">-></button>
</div>
<div class="container text-center d-flex justify-content-center">
	<% @tasks.each_with_index do |task, i|  %>
        	<% unless task.image.nil? %>
          		<span slide="<%= i %>" class="dot"></span>
        	<% end %>

    <% end %>
</div>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_modals.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <%if action == 'log_in'%>

        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Log in</h5>
          <button type="button close" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!-- <h2>Log in</h2> -->
        <div class="modal-body">
        
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>

            <div class="field">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "current-password" %>
            </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
              </div>
            <% end -%>
            
        </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary close" data-dismiss="modal">Close</button>
            <div class="actions">
              <%= f.submit "Log in" %>
            </div>
          </div>
          
        <% end %>

        <%= render "devise/shared/links" %>
      <%elsif action == 'sign_up'%>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Sign up</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!-- <h2>Sign up</h2> -->
        <div class="modal-body">
          
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= render "devise/shared/error_messages", resource: resource %>

            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "new-password" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close" data-dismiss="modal">Close</button>
          <div class="actions">
            <%= f.submit "Sign up" %>
          </div>
        </div>
          
          <% end %>

        <%= render "devise/shared/links" %>
      <%end%>
      


    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
  	</button>
    <%= link_to "Gmail Like", root_path, class: "navbar-brand" %>
  	<div class="collapse navbar-collapse" id="navbarTogglerDemo03">      
  	</div>
  	<div>
  		<img class="rounded-circle avatar" height="50px" width="50px" src="https://www.thehackingproject.org/packs/packs/dashboard/images/profile/default_profile-a3318a5e66467f9958f16a172f9d15d6.jpg">
  	</div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light bg-light dropdown-content">
  	<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    	<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	      	<% unless user_signed_in? %>
	      		<li class="nav-item">
	        		<%= link_to "Log in", new_user_session_path, class: "nav-link", id:"sign-in" %>
	      		</li>
	      		<li class="nav-item">
	        		<%= link_to "Sign up", new_user_registration_path, class: "nav-link", id:"sign-up"  %>
	      		</li>
	      	<% else %>
	      		<li class="nav-item">
	        		<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", id:"log-out"  %>
	      		</li>
	      	<% end %>
	      	<li class="nav-item">
	        	<%= link_to "New task", new_task_path, class: "nav-link" %>
	      	</li>
    	</ul>     
  	</div>
</nav>

app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form", remote: true)  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>

              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag "application" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <aside id='modal1' style='display:none' class = 'modal'>
	  <div class="modal-wrapper">
	    <%=render partial:'layouts/modals', locals:{action:'log_in'}%>
	  </div>
	</aside>
	<aside id='modal2' style='display:none' class = 'modal'>
	  <div class="modal-wrapper">
	    <%=render partial:'layouts/modals', locals:{action:'sign_up'}%>
	  </div>
	</aside>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<li class="task-<%= task.id %>" style="display: none;">
	<%= check_box_tag :name, 1, task.status , data: { remote: true, url: task_path(task), params: { id: task.id}.to_param, method: "put" }%>
    <%= task.title  %>
    <% unless task.deadline.nil? %>
      , to read: <%= task.deadline.strftime('%D')  %>
    <% end %>
    <%= link_to fa_icon("trash"), task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
</li>

app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/create.js.erb
list = document.getElementsByClassName("category-<%= @category.id %>")[0].getElementsByTagName("ul")[0];
list.insertAdjacentHTML("beforeend", "<%= j render 'task', task: @task %>");
listLi = list.getElementsByTagName("li");
newNode = listLi[listLi.length - 1];
$(newNode).fadeIn(500);

app/views/tasks/destroy.js.erb
$(".task-<%= @task.id %>").fadeOut(500);

app/views/tasks/edit.html.erb
<h4>Edit your task</h4>
<%= form_tag(task_path, method: "put") do %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>

  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>
<%= link_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>

app/views/tasks/update.js.erb
myTask = document.getElementsByClassName("task-<%= @task.id %>")[0];
 if (<%= @task.status %>)
{
 	myTask.style.textDecoration = "line-through";
} else {
	myTask.style.textDecoration = "";
}

	      		